
name: checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 16 * * * 
    
jobs:
  build:
    #指定运行环境为最新的Ubuntu版本
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
      #使用action安装node环境
    - name: Use Node.js 15.9.0
      uses: actions/setup-node@v1
      with:
        node-version: 15.9.0
    - run: npm install 
#安装项目依赖
    - run: node index 
#build项目
