
name: Node.js CI
on:
  push:
    branches: [ master ] #监听master分支的push事件
  pull_request:
    branches: [ master ]
jobs:
  build:
    #指定运行环境为最新的Ubuntu版本
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        #指定node版本
        node-version: [15.9.0] 
    steps:
    - uses: actions/checkout@v2
      #使用action安装node环境
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
#安装项目依赖
    - run: node index 
#build项目
